### ISSUE TITLE
If 8bitOperatorPlus-Bold.ttf is not found, game crashes

### ISSUE THREAD

**Issue by baskervald** [adelantis/Undertale-Dating-Simulator#2]
While the obvious way to fix this is to bundle `8bitOperatorPlus-Bold.ttf` into the game, I'd like to recommend the usage of [Determination Mono/Sans](https://www.behance.net/gallery/31268855/Determination-Better-Undertale-Font), since it's more accurate to the original Undertale font. I'll be creating merge requests for each of these options,

**Comment by adelantis** [comment]
Sounds good!

**Comment by baskervald** [comment]
Papyrus.ttf also found to be missing. Papyrus will be added in both.

For future note, issues should only be closed when they're fixed in the codebase, not when decisions are made in regards to them.

**Comment by baskervald** [comment]
It should be noted that the Papyrus.ttf issue is only present on Linux, due to Papyrus being included on both OS X and Windows by default. However, it doesn't seem to be a free font, making things a bit more difficult.

**Comment by baskervald** [comment]
New issue will be created for Papyrus.ttf crash.

Either #3 or #4 should fix this.
